[[grammar]]
name = "asm"
source = { git = "https://github.com/RubixDev/tree-sitter-asm", rev = "b0306e9bb2ebe01c6562f1aef265cc42ccc53070" }

[[language]]
name = "asm"
scope = "source.asm"
roots = []
comment-token = ";"
file-types = ["asm", "S"]
indent = { tab-width = 2, unit = "  " }
grammar = "asm"

[language-server.gpt]
command = "deno"
args = ["run", "--allow-net", "--allow-env", "/Users/alex/Projects/helix-gpt/src/app.ts", "--handler", "openai"]

[[language]]
name = "ruby"
language-servers = [
  "gpt"
]
