#!/bin/bash

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

source "$CONFIG_DIR/colors.sh"

sketchybar --bar position=top height=40 blur_radius=30 color=$BAR_COLOR padding_left=15 padding_right=15

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  background.color="$ITEM_BG_COLOR"
  background.corner_radius=5
  background.drawing=on
  background.border_width=0
  background.height=26
  padding_left=2
  padding_right=2
  icon.font="SF Pro:Semibold:15.0"
  label.font="SF Pro:Semiold:15.0"
  icon.color="$WHITE"
  label.color="$WHITE"
  icon.padding_left=8
  icon.padding_right=8
  label.padding_left=8
  label.padding_right=8
)
sketchybar --default "${default[@]}"

sketchybar --add event aerospace_workspace_change
sketchybar --add event aerospace_monitor_change

# -- Left side items - ---

for sid in $(aerospace list-workspaces --all); do
  sketchybar --add item space.$sid left \
    --set space.$sid \
    display="$(
      v=$(aerospace list-windows --workspace "$sid" --format "%{monitor-appkit-nsscreen-screens-id}" | cut -c1)
      echo "${v:-1}"
    )" \
    drawing=off \
    icon="$sid" \
    label.font="sketchybar-app-font:Regular:16.0" \
    label.padding_right=8 \
    label.padding_left=0 \
    label.y_offset=-1 \
    click_script="aerospace workspace $sid"
done

sketchybar --add item front_app left \
           --subscribe front_app front_app_switched \
           --set front_app \
                 icon.font="sketchybar-app-font:Regular:16.0" \
                 script="$PLUGIN_DIR/front_app.sh"

# hidden placeholder to run script to update all space items in one pass
sketchybar --add item spaces left \
           --subscribe spaces aerospace_workspace_change \
           --set spaces drawing=off \
                        script="$CONFIG_DIR/plugins/aerospace.sh"

source "$PLUGIN_DIR/aerospace.sh"

# -- Right side items

sketchybar --add item clock right \
           --set clock update_freq=10 icon.padding_left=0 script="$PLUGIN_DIR/clock.sh" \
           --add item battery right \
           --set battery update_freq=120 label.padding_left=0 label.padding_right=0 icon.padding_left=8 icon.padding_right=8 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
